steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'github.com/grevian/GoGame/server']
  env: ['PROJECT_ROOT=github.com/grevian/GoGame']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gogame', '.']
images: ['gcr.io/$PROJECT_ID/gogame']

