steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'auth_service']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/go'
  args: ['install', 'platformer_service']
  env: ['GOPATH=.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gogame-auth', './auth_service']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gogame-platformer', './platformer_service']
images: ['gcr.io/$PROJECT_ID/gogame-auth']
images: ['gcr.io/$PROJECT_ID/gogame-platformer']

